[package]
name = "peri-mcp-web"
version.workspace = true
edition.workspace = true
description = "Builtin web MCP instance for Peri"
license = "Apache-2.0"

[dependencies]
async-trait.workspace = true
peri-agent = { path = "../../peri-agent" }
peri-mcp-common = { path = "../common" }
reqwest = { workspace = true, features = ["gzip", "brotli", "deflate"] }
rmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
peri-acp-types = { path = "../../peri-acp-types" }
rmcp = { workspace = true, features = ["client"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
tokio = { workspace = true, features = ["full"] }
