import type { MetaHarnessKey } from "./peri-config";

/** Start with every known MetaHarness section and capability disabled. */
export const BareHarnessConfig = Object.freeze({
  "01_intro": false,
  "02_system": false,
  "03_doing_tasks": false,
  "04_actions": false,
  "05_using_tools": false,
  "06_tone_style": false,
  "07_runtime": false,
  "10_hitl": false,
  "11_subagent": false,
  "12_ask_user": false,
  "13_skills": false,
  persona: false,
  language: false,
  DefaultSystemPromptMiddleware: false,
  LangMiddleware: false,
  AgentsMdMiddleware: false,
  PluginMiddleware: false,
  SkillsMiddleware: false,
  SkillPreloadMiddleware: false,
  AtMentionMiddleware: false,
  ImageMiddleware: false,
  GitAttributionMiddleware: false,
  TodoMiddleware: false,
  HookMiddleware: false,
  PermissionMiddleware: false,
  HumanInTheLoopMiddleware: false,
  SubAgentMiddleware: false,
  McpMiddleware: false,
  WorkflowMiddleware: false,
  PtcMiddleware: false,
  ToolSearch: false,
  LspSyncMiddleware: false,
  GoalMiddleware: false,
  WebMiddleware: false,
  ArtifactMiddleware: false,
  CronMiddleware: false,
  LspMiddleware: false,
  WorkspaceMiddleware: false,
  BuiltInSubagents: false,
} satisfies Record<MetaHarnessKey, false>);
