[target.i686-unknown-linux-musl]
# The 32-bit Linux distribution is standalone, including the musl CRT.
rustflags = ["-C", "target-feature=+crt-static"]

[target.loongarch64-unknown-linux-musl]
# The 64-bit LoongArch distribution is standalone, including the musl CRT.
rustflags = ["-C", "target-feature=+crt-static"]
